"""Impoved security

Revision ID: 3157e2c135a7
Revises: 7f4ad4d2692d
Create Date: 2023-11-12 21:47:47.128209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3157e2c135a7'
down_revision = '7f4ad4d2692d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
